export type LabelLanguage = "id" | "en";

export const DEGREE_LABELS = {
  id: {
    middle_school: "SMP",
    high_school: "SMA/SMK",
    associate_d1: "D1",
    associate_d2: "D2",
    associate_d3: "D3",
    bachelor: "Sarjana",
    master: "Magister",
    doctorate: "Doktor",
    any: "Semua Jenjang",
  },
  en: {
    middle_school: "Middle School",
    high_school: "High School",
    associate_d1: "Associate (D1)",
    associate_d2: "Associate (D2)",
    associate_d3: "Associate (D3)",
    bachelor: "Bachelor",
    master: "Master",
    doctorate: "Doctorate",
    any: "Any",
  },
} as const satisfies Record<LabelLanguage, Record<string, string>>;

export const JOB_TYPE_LABELS = {
  id: {
    full_time: "Penuh Waktu",
    contract: "Kontrak",
    internship: "Magang",
    freelance: "Freelance",
    part_time: "Paruh Waktu",
  },
  en: {
    full_time: "Full Time",
    contract: "Contract",
    internship: "Internship",
    freelance: "Freelance",
    part_time: "Part Time",
  },
} as const satisfies Record<LabelLanguage, Record<string, string>>;

export const SKILL_LEVEL_LABELS = {
  id: {
    beginner: "Pemula",
    intermediate: "Menengah",
    advanced: "Lanjutan",
    expert: "Ahli",
  },
  en: {
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    expert: "Expert",
  },
} as const satisfies Record<LabelLanguage, Record<string, string>>;

export const ORGANIZATION_TYPE_LABELS = {
  id: {
    student: "Mahasiswa",
    community: "Komunitas",
    professional: "Profesional",
    volunteer: "Relawan",
    other: "Lainnya",
  },
  en: {
    student: "Student",
    community: "Community",
    professional: "Professional",
    volunteer: "Volunteer",
    other: "Other",
  },
} as const satisfies Record<LabelLanguage, Record<string, string>>;

export const PLATFORM_LABELS = {
  id: {
    linkedin: "LinkedIn",
    website: "Website",
    blog: "Blog",
    portfolio: "Portofolio",
    github: "GitHub",
    gitlab: "GitLab",
    bitbucket: "Bitbucket",
    stackoverflow: "Stack Overflow",
    devto: "Dev.to",
    hashnode: "Hashnode",
    medium: "Medium",
    leetcode: "LeetCode",
    hackerrank: "HackerRank",
    codewars: "Codewars",
    topcoder: "Topcoder",
    kaggle: "Kaggle",
    behance: "Behance",
    dribbble: "Dribbble",
    figma: "Figma",
    adobe_portfolio: "Adobe Portfolio",
    artstation: "ArtStation",
    youtube: "YouTube",
    vimeo: "Vimeo",
    tiktok: "TikTok",
    twitch: "Twitch",
    x: "X",
    instagram: "Instagram",
    facebook: "Facebook",
    threads: "Threads",
    discord: "Discord",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    line: "LINE",
    wechat: "WeChat",
    skype: "Skype",
    google_scholar: "Google Scholar",
    orcid: "ORCID",
    researchgate: "ResearchGate",
    arxiv: "arXiv",
  },
  en: {
    linkedin: "LinkedIn",
    website: "Website",
    blog: "Blog",
    portfolio: "Portfolio",
    github: "GitHub",
    gitlab: "GitLab",
    bitbucket: "Bitbucket",
    stackoverflow: "Stack Overflow",
    devto: "Dev.to",
    hashnode: "Hashnode",
    medium: "Medium",
    leetcode: "LeetCode",
    hackerrank: "HackerRank",
    codewars: "Codewars",
    topcoder: "Topcoder",
    kaggle: "Kaggle",
    behance: "Behance",
    dribbble: "Dribbble",
    figma: "Figma",
    adobe_portfolio: "Adobe Portfolio",
    artstation: "ArtStation",
    youtube: "YouTube",
    vimeo: "Vimeo",
    tiktok: "TikTok",
    twitch: "Twitch",
    x: "X",
    instagram: "Instagram",
    facebook: "Facebook",
    threads: "Threads",
    discord: "Discord",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    line: "LINE",
    wechat: "WeChat",
    skype: "Skype",
    google_scholar: "Google Scholar",
    orcid: "ORCID",
    researchgate: "ResearchGate",
    arxiv: "arXiv",
  },
} as const satisfies Record<LabelLanguage, Record<string, string>>;

export const PROJECT_LINK_LABELS = {
  id: {
    repo: "Repositori",
    live: "Live Demo",
  },
  en: {
    repo: "Repository",
    live: "Live Demo",
  },
} as const satisfies Record<LabelLanguage, Record<"repo" | "live", string>>;
